In [70]:
import numpy as np

In [10]:
a = np.array([11,12,13,14,15])
print(a)
print(type(a))

[11 12 13 14 15]
<class 'numpy.ndarray'>


In [11]:
a1 = np.asarray([21,21,23,24,25])
print(a1)
print(type(a1))

[21 21 23 24 25]
<class 'numpy.ndarray'>


In [14]:
a2 = np.arange(3,21)
print(a2)
print(type(a2))
print(len(a2))

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
18


### Indexing and Slicing in 1D array

In [15]:
a = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25])
print(a)
print(type(a))
print(len(a))

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
<class 'numpy.ndarray'>
14


In [17]:
# Indexing in 1D array
print(a[0]) # 12
print(a[4]) # 16
print(a[8]) # 20 
print(a[-2]) # 19 
print(a[-7]) # 14
print(a[-5]) # 16

12
16
20
24
19
21


In [18]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [20]:
# Slicing in 1D array
print(a)
print(a[2:5])
print(a[3:])
print(a[:6])
print(a[-4:])
print(a[:-6])
print(a[:])
print(a[1:8:2])
print(a[3:-7])
print(a[3:-7:2])
print(a[-2:-8:-2])
print(a[-2:3:-3])
print(a[3:8:3])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16]
[15 16 17 18 19 20 21 22 23 24 25]
[12 13 14 15 16 17]
[22 23 24 25]
[12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[13 15 17 19]
[15 16 17 18]
[15 17]
[24 22 20]
[24 21 18]
[15 18]


In [15]:
# Slicing in 1D array - special cases
print(a)
print('----------')
print(a[::-1]) #Reverse
print('-----------')
print(a[3:-2])
print('-----------')
print(a[-2:-11])
print('-----------')
print(a[3:-4:-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
----------
[25 24 23 22 21 20 19 18 17 16 15 14 13 12]
-----------
[15 16 17 18 19 20 21 22 23]
-----------
[]
-----------
[]


### Indexing and Slicing in 2D array

In [24]:
b = np.array([[31,32,33,34],[35,36,37,38],
              [39,40,41,42],[43,44,45,46]])
print(b)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]


In [26]:
# Indexing in 2D array
print(b[2][0])
print(b[-1][-2])
print(b[2][-3])
print(b[-1][3])

39
45
40
46


In [27]:
print(b)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]


In [28]:
# Indexing and Slicing in 2D array
print(b[2])
print('-----------')
print(b[3:])
print('-----------')
print(b[2:,:])
print('-----------')
print(b[:,1:])
print('-----------')
print(b[2:,1:])
print('-----------')
print(b[:2,:2])

[39 40 41 42]
-----------
[[43 44 45 46]]
-----------
[[39 40 41 42]
 [43 44 45 46]]
-----------
[[32 33 34]
 [36 37 38]
 [40 41 42]
 [44 45 46]]
-----------
[[40 41 42]
 [44 45 46]]
-----------
[[31 32]
 [35 36]]


In [29]:
print(b)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]


In [32]:
print(b[-1])
print('--------')
print(b[:-1])
print('--------')
print(b[:,-1])
print('--------')
print(b[-2,:-2])

[43 44 45 46]
--------
[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]]
--------
[34 38 42 46]
--------
[39 40]


In [33]:
print(b)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]


In [42]:
print(b[-2:,:-1])

[[39 40 41]
 [43 44 45]]


In [43]:
print(b[1:,2:])

[[37 38]
 [41 42]
 [45 46]]


In [44]:
print(b[:2,0:])

[[31 32 33 34]
 [35 36 37 38]]


In [34]:
# Slicing in 2d array
print(b[::2,:])

[[31 32 33 34]
 [39 40 41 42]]


In [35]:
print(b[:2,::2])

[[31 33]
 [35 37]]


In [36]:
print(b[1::2,1::2])

[[36 38]
 [44 46]]


In [37]:
print(b[0::2,0::3])

[[31 34]
 [39 42]]


In [41]:
print(b[-4::-2,-3])

[32]


In [42]:
print(b[-4::-2,-3::-1])

[[32 31]]


In [43]:
b[0:,:2]

array([[31, 32],
       [35, 36],
       [39, 40],
       [43, 44]])

In [51]:
### Advanced Indexing
b

array([[31, 32, 33, 34],
       [35, 36, 37, 38],
       [39, 40, 41, 42],
       [43, 44, 45, 46]])

In [45]:
b[[0,2,1,3],[1,3,2,1]]

array([32, 42, 37, 44])

In [46]:
b[[0,2],[1,3]]

array([32, 42])

In [55]:
b[[2,1,2,0],[3,0,2,1]]

array([42, 35, 41, 32])

In [47]:
b[[0,1,2,3],[0,1,2,3]]

array([31, 36, 41, 46])

In [48]:
b[[2,1,2,0],[3,0,2,1]]

array([42, 35, 41, 32])

In [49]:
b[[0,1,2,3],[0,1,2,3]]

array([31, 36, 41, 46])

In [51]:
b[[0,1,2,3],[3,2,1,0]]

array([34, 37, 40, 43])

### Indexing and Slicing in 3D 

In [77]:
a = np.arange(24).reshape(2,4,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [54]:
# Indexing in 3D array
print(a[0][2][1])
print(a[1][3][0])
print(a[-1])
print(a[-2])

7
21
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
# print(a[-2])
print(a[-1][-2])
print(a[-1][-2][-3])

[18 19 20]
18


In [57]:
print(a[-2][0][-1])
print(a)

2
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [58]:
## Slicing in 3d array
print(a[1:,1:,2:])
print('----------')
print(a[1:,:2,:2])
print('----------')
print(a[0:1,3:,1:])

[[[17]
  [20]
  [23]]]
----------
[[[12 13]
  [15 16]]]
----------
[[[10 11]]]


In [11]:
print(a[0:,1::2,:2])

[[[ 3  4]
  [ 9 10]]

 [[15 16]
  [21 22]]]


In [59]:
print(a[0:,1:3,0::2])

[[[ 3  5]
  [ 6  8]]

 [[15 17]
  [18 20]]]


In [60]:
# Negative slicing in 3d array
print(a[-1:,:,:])

[[[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [61]:
print(a[:-1,:,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [62]:
print(a[-1:,-2:,:])

[[[18 19 20]
  [21 22 23]]]


In [129]:
print(a[-1::-1,-2:,:])

[[[18 19 20]
  [21 22 23]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [79]:
print(a[-1:,:-2,:])

[[[12 13 14]
  [15 16 17]]]


In [80]:
print(a[-1:,:-2,-1:])

[[[14]
  [17]]]


In [81]:
print(a[-2,:-1,-2])

[1 4 7]


In [84]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [98]:
print(a[-2,-1::-2,-1::-2])

[[11  9]
 [ 5  3]]


In [96]:
print(a[-2:,-2::-2,-1::-2])

[[[ 8  6]
  [ 2  0]]

 [[20 18]
  [14 12]]]


In [102]:
print(a[-2:,-1::-2,1])

[[10  4]
 [22 16]]


In [104]:
print(a[-2:,-1::-3,-1::-2])

[[[11  9]
  [ 2  0]]

 [[23 21]
  [14 12]]]


In [122]:
print(a[-2:,-1::-2,1:3])

[[[10 11]
  [ 4  5]]

 [[22 23]
  [16 17]]]


In [127]:
print(a[-2:,-2:-4:-1,-1::-2])

[[[ 8  6]
  [ 5  3]]

 [[20 18]
  [17 15]]]


In [126]:
print(a[0:,1:3,1:2])

[[[ 4]
  [ 7]]

 [[16]
  [19]]]


In [113]:
print(a[0:,::3,::2])

[[[ 0  2]
  [ 9 11]]

 [[12 14]
  [21 23]]]


In [125]:
print(a[:,0::3,0::2])

[[[ 0  2]
  [ 9 11]]

 [[12 14]
  [21 23]]]


In [121]:
print(a[0:,1:3,1])

[[ 4  7]
 [16 19]]


In [116]:
# Advanced slicing
print(a[a>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [117]:
print(a[a%5!=0])

[ 1  2  3  4  6  7  8  9 11 12 13 14 16 17 18 19 21 22 23]


In [118]:
a[[0,1,0,1],[1,2,3,0],[2,0,1,2]]

array([ 5, 18, 10, 14])

In [119]:
a[[0,0,0,0],[0,1,2,3],[0,1,2,2]]

array([ 0,  4,  8, 11])